- name: Uninstall the cluster when invoked via tags
  block:
  - name: uninstall k3s from servers
    ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
    when: inventory_hostname in groups['servers']
    args:
      removes: /usr/local/bin/k3s-uninstall.sh

  - name: uninstall k3s from agents
    ansible.builtin.command: /usr/local/bin/k3s-agent-uninstall.sh
    when: inventory_hostname in groups['agents']
    args:
      removes: /usr/local/bin/k3s-agent-uninstall.sh

  - name: Disable and stop checksum offload disable service
    systemd:
      name: "{{ checksum_service_name }}"
      enabled: no
      state: stopped

  - name: Remove flannel checksum service file
    ansible.builtin.file:
      path: "/etc/systemd/system/{{ checksum_service_name }}.service"
      state: absent

  - name: Remove flannel checksum script file
    ansible.builtin.file:
      path: "{{ checksum_script_path }}"
      state: absent

  - name: Reload systemd to pick up removal of checksum service
    ansible.builtin.command: systemctl daemon-reload
    changed_when: true

  when: "'k3s-uninstall' in ansible_run_tags"
  tags: k3s-uninstall