# Install the nfs csi driver
- name: Install the pre-reqs
  block:
  - name: Install the nfs csi driver helm repo
    kubernetes.core.helm_repository:
      name: csi-driver-nfs
      binary_path: /usr/local/bin/helm
      repo_url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
      kubeconfig: "{{ role_path }}/../../kubeconfig.yaml"

  - name: Install the nfs csi driver via helm
    kubernetes.core.helm:
      name: csi-driver-nfs
      binary_path: /usr/local/bin/helm
      kubeconfig: "{{ role_path }}/../../kubeconfig.yaml"
      chart_ref: csi-driver-nfs/csi-driver-nfs
      namespace: csi-driver-nfs
      create_namespace: true
      values:
        controller:
          runOnControlPlane: "true"
          replicas: "2"
        externalSnapshotter:
          enabled: "false"
#      set_values:
#        - controller.runOnControlPlane: "true"
#        - controller.replicas: "2"
#        - controller.strategyType: "RollingUpdate"
#        - externalSnapshotter.enabled: "false"
      wait: true
#      timeout: "300"

  - name: Install the nginx ingress helm repo
    kubernetes.core.helm_repository:
      name: ingress-nginx
      binary_path: /usr/local/bin/helm
      kubeconfig: "{{ role_path }}/../../kubeconfig.yaml"
      repo_url: https://kubernetes.github.io/ingress-nginx
      state: present

  - name: Install the nginx ingress via helm
    kubernetes.core.helm:
      name: ingress-nginx
      binary_path: /usr/local/bin/helm
      kubeconfig: "{{ role_path }}/../../kubeconfig.yaml"
      chart_ref: ingress-nginx/ingress-nginx
      namespace: ingress-nginx
      create_namespace: true
      wait: true

#  - name: Install the community cert-manager helm repo
#    kubernetes.core.helm_repository:
#      name: jetstack
#      binary_path: /usr/local/bin/helm
#      kubeconfig: "{{ role_path }}/../../kubeconfig.yaml"
#      repo_url: oci://quay.io/jetstack/charts/cert-manager
#      state: present
      
  - name: Install the cert-manager via helm
    kubernetes.core.helm:
      name: cert-manager
      binary_path: /usr/local/bin/helm
      kubeconfig: "{{ role_path }}/../../kubeconfig.yaml"
      chart_ref: "oci://quay.io/jetstack/charts/cert-manager"
      chart_version: "{{ certmanager_version }}"
      namespace: cert-manager
      create_namespace: true
      values:
        crds:
          enabled: true
      wait: true

  delegate_to: localhost
  run_once: true
  tags: install_concert, pre-reqs

